### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [TaoLyn838/IOS102-Pre-work-Introduce-Yourself#1]
Thanks for submitting your prework assignment. Upon our review of your work, we noticed that the GIF or recording included in your submission did not show the following features:

 - The stepper changes the number of pets.

This made your assignment incomplete. Kindly record another demo **showing all required features.** Once done, resubmit your assignment in the application dashboard.

**Comment by TaoLyn838** [comment]
Thanks for the feedback! 🙂 I made a new recording and updated my App walk though and README file. Also, I resubmit my GIF URL in Application Status!
